input {

  jdbc {
    jdbc_driver_library => "/usr/share/logstash/drivers/mssql-jdbc-13.4.0.jre11.jar"
    jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"

    jdbc_connection_string => "jdbc:sqlserver://host.docker.internal:1433;databaseName=TechTraders_tgdb;encrypt=false"

    jdbc_user => "automation_user"
    jdbc_password => "Password@123"

    statement => "
        SELECT
            audit_id,
            method,
            endpoint,
            status_code,
            response_time_ms,
            ip_address,
            created_at
        FROM dbo.audit_log
        WHERE audit_id > :sql_last_value
        ORDER BY audit_id
    "

    use_column_value => true
    tracking_column => "audit_id"
    tracking_column_type => "numeric"

    schedule => "*/30 * * * * *"

    last_run_metadata_path => "/usr/share/logstash/state/audit_log.yml"

    add_field => {
      "pipeline" => "audit"
    }
  }

}

filter {

    if [pipeline] == "audit" {

        mutate {
          convert => {
            "audit_id" => "integer"
            "status_code" => "integer"
            "response_time_ms" => "integer"
          }
        }
        
        geoip {
          source => "ip_address"
          target => "geoip"
        }
    }
}

output {

  if [pipeline] == "audit" {

    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "audit-logs"
      document_id => "%{audit_id}"
    }

  }

  stdout {
    codec => rubydebug
  }

}