USE [master]
GO

/****** Object:  Database [Ourfirstdatabase]    Script Date: 2026/05/11 15:52:17 ******/
CREATE DATABASE [Ourfirstdatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ourfirstdatabase', FILENAME = N'C:\sc_TeolanGovender_2026\DatabaseAdministration\CourseFolders\SQL_DATA_FILES\Ourfirstdatabase.mdf' , SIZE = 65536KB , MAXSIZE = 1048576KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Ourfirstdatabase_log', FILENAME = N'C:\sc_TeolanGovender_2026\DatabaseAdministration\CourseFolders\SQL_LOG_FILES\Ourfirstdatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 524288KB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ourfirstdatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Ourfirstdatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Ourfirstdatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Ourfirstdatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Ourfirstdatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Ourfirstdatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Ourfirstdatabase] SET  MULTI_USER 
GO

ALTER DATABASE [Ourfirstdatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Ourfirstdatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Ourfirstdatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Ourfirstdatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Ourfirstdatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Ourfirstdatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Ourfirstdatabase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Ourfirstdatabase] SET  READ_WRITE 
GO


