name: Reusable SQL Deploy

on:
  workflow_call:
    inputs:
      server:
        required: true
        type: string
      port:
        required: true
        type: string
      username:
        required: true
        type: string
      database:
        required: true
        type: string
      scripts_path:
        required: true
        type: string

    secrets:
      sql_password:
        required: true


jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #FAIL FAST CHECK (prevents empty sqlcmd args)
      - name: Validate Inputs
        shell: powershell
        run: |
          if ([string]::IsNullOrWhiteSpace("${{ inputs.server }}")) { throw "SERVER is empty" }
          if ([string]::IsNullOrWhiteSpace("${{ inputs.port }}")) { throw "PORT is empty" }
          if ([string]::IsNullOrWhiteSpace("${{ inputs.username }}")) { throw "USERNAME is empty" }
          if ([string]::IsNullOrWhiteSpace("${{ secrets.sql_password }}")) { throw "PASSWORD is empty" }

      - name: Create Database
        shell: powershell
        run: |
          sqlcmd `
            -b `
            -S "${{ inputs.server }},${{ inputs.port }}" `
            -U "${{ inputs.username }}" `
            -P "${{ secrets.sql_password }}" `
            -Q "IF DB_ID('${{ inputs.database }}') IS NULL CREATE DATABASE ${{ inputs.database }};"

      - name: Run SQL Scripts
        shell: powershell
        run: |
          $server = "${{ inputs.server }},${{ inputs.port }}"
          $user = "${{ inputs.username }}"
          $pass = "${{ secrets.sql_password }}"
          $db = "${{ inputs.database }}"
          $path = "${{ inputs.scripts_path }}"

          sqlcmd -b -S $server -U $user -P $pass -d $db -i "$path/CreateTable.sql"
          sqlcmd -b -S $server -U $user -P $pass -d $db -i "$path/CreateLoggingTable.sql"
          sqlcmd -b -S $server -U $user -P $pass -d $db -i "$path/SeedData.sql"
          sqlcmd -b -S $server -U $user -P $pass -d $db -i "$path/LogExecution.sql"
